# Debate System Configuration
debate:
  # Maximum number of rounds
  max_rounds: 5
  
  # Participating Agents
  agents:
    - Agent_A
    - Agent_B
    - Agent_C
  
  # Default debate topic
  default_topic: "Should artificial intelligence be regulated by the government?"
  
  # Agent initial settings
  agent_configs:
    Agent_A:
      initial_stance: 0.8    # Supporting stance
      initial_conviction: 0.7
      personality: "analytical"
      strategy_preference:   # Strategy preference
        analytical: 0.4
        empathetic: 0.3
        defensive: 0.2
        aggressive: 0.1
    Agent_B:
      initial_stance: -0.6   # Opposing stance
      initial_conviction: 0.6
      personality: "aggressive"
      strategy_preference:
        aggressive: 0.4
        defensive: 0.3
        analytical: 0.2
        empathetic: 0.1
    Agent_C:
      initial_stance: 0.0    # Neutral stance
      initial_conviction: 0.5
      personality: "empathetic"
      strategy_preference:
        empathetic: 0.4
        analytical: 0.3
        defensive: 0.2
        aggressive: 0.1
  
  # Victory condition settings
  victory_conditions:
    surrender_threshold: 0.4      # Conviction below this value may surrender
    stance_neutral_threshold: 0.2 # Threshold for stance approaching neutral
    consecutive_persuasion: 3     # Number of consecutive rounds being persuaded
    
  # Persuasion calculation
  persuasion_factors:
    base_persuasion: 0.3         # Base persuasion power
    strategy_bonus: 0.2          # Strategy bonus
    evidence_bonus: 0.3          # Evidence bonus
    social_influence: 0.2        # Social influence bonus

# GPT Settings
gpt:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 500
  system_prompt: |
    You are an intelligent agent participating in public issue debates.
    Please present persuasive arguments based on your stance and strategy.
    Use rationality, logic, and evidence to support your viewpoints.

# Parallel Processing Settings
parallel:
  max_workers: 4
  timeout: 30  # seconds
  
  # Module parallel settings
  module_priorities:
    rl: 1      # Highest priority
    gnn: 2
    rag: 3

# Strategy Fusion Settings
strategy_fusion:
  # Fusion method
  method: "weighted_average"  # weighted_average, voting, adaptive
  
  # Weight allocation
  weights:
    rl_policy: 0.4      # RL strategy weight
    gnn_suggestion: 0.3 # GNN suggestion weight
    personality: 0.3    # Personality preference weight
  
  # Adaptive adjustment
  adaptive:
    enabled: true
    learning_rate: 0.1

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Module-specific logging
  module_logging:
    rl: "DEBUG"
    gnn: "INFO"
    rag: "INFO"
    orchestrator: "DEBUG"