# GNN (Graph Neural Network) Configuration

# Model Architecture
model:
  # Supervised learning architecture
  architecture: "PersuasionGNN"
  
  # Dimension settings
  input_dim: 770         # BERT (768) + argument features (2)
  hidden_dim: 256       # Hidden layer dimension
  output_dim: 128       # Embedding vector dimension
  
  # Network layers
  num_layers: 3
  
  # Regularization
  dropout: 0.2
  
  # Activation function
  activation: "relu"
  
  # Graph convolution type
  conv_type: "GraphSAGE"  # Use GraphSAGE
  
  # Attention mechanism
  attention:
    enabled: true
    heads: 4
    concat: false

# Training Settings
training:
  # Basic parameters
  epochs: 50
  learning_rate: 0.001
  batch_size: 32
  
  # Optimizer
  optimizer: "adam"
  weight_decay: 0.0001
  
  # Learning rate scheduling
  scheduler:
    type: "step"
    step_size: 10
    gamma: 0.5
  
  # Early stopping
  early_stopping:
    patience: 10
    min_delta: 0.001
    
  # Multi-task weights
  task_weights:
    delta_prediction: 0.5    # Delta prediction weight
    quality_regression: 0.3  # Quality score weight
    strategy_classification: 0.2  # Strategy classification weight

# Persuasion Prediction Settings
persuasion_prediction:
  # Strategy categories
  strategies:
    - aggressive    # Aggressive attack type
    - defensive     # Defensive rebuttal type
    - analytical    # Analytical argument type
    - empathetic    # Empathetic persuasion type
  
  # Argument feature extraction
  argument_features:
    causal_markers: ["because", "therefore", "thus", "hence", "consequently"]
    contrast_markers: ["however", "but", "although", "despite", "nevertheless"]
    evidence_markers: ["studies show", "research indicates", "data suggests", "according to"]
    example_markers: ["for example", "for instance", "such as", "like"]
    emphasis_markers: ["indeed", "in fact", "clearly", "obviously", "certainly"]

# Social Influence Calculation
social_influence:
  # Influence calculation method
  method: "model_based"  # Based on model prediction
  
  # Weight allocation
  weights:
    delta_probability: 0.7
    quality_score: 0.3

# Model Saving Settings
checkpointing:
  save_dir: "data/models"
  model_name: "gnn_persuasion.pt"
  save_best_only: true
  monitor_metric: "delta_accuracy"

# Evaluation Settings
evaluation:
  # Evaluation metrics
  metrics:
    - delta_accuracy
    - delta_f1_score
    - strategy_accuracy
    - quality_mse
  
  # Test set ratio
  test_split: 0.2
  
  # Random seed
  random_seed: 42

# Logging Settings
logging:
  level: "INFO"
  log_dir: "logs/gnn"
  tensorboard: false
